name: Deploy Angular App to S3

on:
  push:
    branches:
      - main # or your deployment branch


permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your project's version

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Install dependencies
        run: npm ci

      - name: Create production environment file
        run: |
          cat > src/environments/environment.ts << EOF
          export const environment = {
            production: true,
            openRouteServiceApiKey: '${{ secrets.OPEN_ROUTE_SERVICE_API_KEY }}',
            openAipApiKey: '',
            flightApi: {
              url: 'sky-scanner3.p.rapidapi.com',
              key: '${{ secrets.FLIGHT_API_KEY }}',
            },
            auth0: {
              domain: '${{ secrets.AUTH0_DOMAIN }}',
              clientId: '${{ secrets.AUTH0_CLIENT_ID }}',
            }
          };
          EOF

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Deploy to S3
        run: aws s3 sync dist/frontend/browser s3://${{ secrets.AWS_S3_BUCKET }} --delete
